version: 2.1

jobs:
  build-image:
    machine:
      image: ubuntu-2004:2023.07.1
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_ACCESS_TOKEN" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build (and maybe push) multi-arch images
          command: |
            docker buildx create --use
            TAG_NAME=$(date +%Y-%m-%d-%H-%M-%S)
            docker buildx build --platform linux/arm64 \
              --file Dockerfile \
              --progress plain \
              --tag $DOCKERHUB_USERNAME/graphhopper:${TAG_NAME} \
              $(if [ "$CIRCLE_BRANCH" = "master" ]; then echo '--push'; fi) .

workflows:
  my-workflow:
    jobs:
      - build-image:
          context:
            - docker-hub
